enum class TokenType {
    IDENTIFIER, STRING, NUMBER, BOOLEAN, ANY,

    ADDED, SUBTRACTED, MULTIPLIED, DIVIDED, BY,

    AND, OR, NOT, IS, EQUAL, GREATER, LESS, THAN,

    SET, TO, AS, THIS,

    IF, THEN, OTHERWISE, END_IF,

    WHILE, DO, FOR, END_WHILE, END_FOR,

    BLOCK, END_BLOCK,

    BASED, WHEN, ESCAPE, END_BASED,

    SHOW, QUIT,

    COMMA,

    EOL, EOF,

    INVALID,

    OPEN_PARENTHESIS, CLOSE_PARENTHESIS,

    USING, ONLY,

    CONCAT
}