enum class TokenType {
    IDENTIFIER, STRING, NUMBER, BOOLEAN, ANY,

    ADDED, SUBTRACTED, MULTIPLIED, DIVIDED, BY,

    AND, OR, NOT, IS, EQUAL, GREATER, LESS, THAN,

    SET, TO, AS,

    IF, THEN, OTHERWISE, END,

    WHILE, DO, FOR,

    BASED, WHEN, ESCAPE,

    SHOW,

    COMMA,

    EOL, EOF,

    INVALID,

    OPEN_PARENTHESIS, CLOSE_PARENTHESIS
}